{% set name = "starlette-compress" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/starlette_compress-{{ version }}.tar.gz
  sha256: 7ebfb0555109341f192a773c660e66737c82ca42e7c5ff1cb2a057af0aea3716

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - brotli-python >=1
    - starlette
    - zstandard >=0.15

test:
  imports:
    - starlette_compress
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Zaczero/starlette-compress
  summary: Compression middleware for Starlette - supporting ZStd, Brotli, and GZip
  license: 0BSD

extra:
  recipe-maintainers:
    - dennis-wey
